export const CampaignsActionTypes = {
    REQUEST_CAMPAIGNS_PENDING: 'REQUEST_CAMPAIGNS_PENDING',
    REQUEST_CAMPAIGNS_SUCCESS: 'REQUEST_CAMPAIGNS_SUCCESS',
    REQUEST_CAMPAIGNS_FAILED: 'REQUEST_CAMPAIGNS_FAILED',
};
